CREATE TABLE Person(
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    firstName VARCHAR(255),
    lastName VARCHAR(255),
    age INT
);

CREATE TABLE Address(
    ownerId INT,
    street VARCHAR(255),
    zip INT
);

CREATE TABLE Product(
  description VARCHAR(255),
  id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  sku NUMBER
);

CREATE TABLE KmpTestEntity(
    timeLocalDate      DATE,                     -- java.time.LocalDate
    timeLocalTime      TIMESTAMP,                     -- java.time.LocalTime
    timeLocalDateTime  TIMESTAMP,                -- java.time.LocalDateTime
    timeInstant        TIMESTAMP WITH TIME ZONE,  -- java.time.Instant
    timeLocalDateOpt      DATE,
    timeLocalTimeOpt      TIMESTAMP,                     -- java.time.LocalTime
    timeLocalDateTimeOpt  TIMESTAMP,                -- java.time.LocalDateTime
    timeInstantOpt        TIMESTAMP WITH TIME ZONE  -- java.time.Instant
);

CREATE TABLE TimeEntity(
    sqlDate        DATE,                     -- java.sql.Date
    -- Oracle has no TIME type
    sqlTime        TIMESTAMP,                     -- java.sql.Time
    sqlTimestamp   TIMESTAMP,                -- java.sql.Timestamp
    timeLocalDate      DATE,                     -- java.time.LocalDate
    timeLocalTime      TIMESTAMP,                     -- java.time.LocalTime
    timeLocalDateTime  TIMESTAMP,                -- java.time.LocalDateTime
    timeZonedDateTime  TIMESTAMP WITH TIME ZONE, -- java.time.ZonedDateTime
    timeInstant        TIMESTAMP WITH TIME ZONE, -- java.time.Instant
    timeOffsetTime     TIMESTAMP WITH TIME ZONE,      -- java.time.OffsetTime
    timeOffsetDateTime TIMESTAMP WITH TIME ZONE  -- java.time.OffsetDateTime
);

CREATE TABLE EncodingTestEntity(
  stringMan VARCHAR(255),
  booleanMan SMALLINT,
  byteMan SMALLINT,
  shortMan SMALLINT,
  intMan INTEGER,
  longMan NUMBER,
  floatMan FLOAT,
  doubleMan DOUBLE PRECISION,
  byteArrayMan BLOB,
  customMan VARCHAR(255),
  stringOpt VARCHAR(255),
  booleanOpt SMALLINT,
  byteOpt SMALLINT,
  shortOpt SMALLINT,
  intOpt INTEGER,
  longOpt NUMBER,
  floatOpt FLOAT,
  doubleOpt DOUBLE PRECISION,
  byteArrayOpt BLOB,
  customOpt VARCHAR(255)
);

CREATE TABLE JavaTestEntity(
  bigDecimalMan DECIMAL(5,2),
  javaUtilDateMan TIMESTAMP,
  uuidMan VARCHAR(36),
  bigDecimalOpt DECIMAL(5,2),
  javaUtilDateOpt TIMESTAMP,
  uuidOpt VARCHAR(36)
);
