name: CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: 'Run Jdbc, Android, and Native-Linux Tests'
        if: matrix.os == 'ubuntu-latest'
        run: >-
          docker compose build && docker compose run --rm --service-ports setup &&
          ./gradlew build --stacktrace -PisCI -Pnosign

      - name: 'Run MacOS Tests'
        if: matrix.os == 'macOS-latest'
        run: ./gradlew :terpal-sql-native:build --stacktrace -PisCI -Pnosign

      - name: 'Run windows tests'
        if: matrix.os == 'windows-latest'
        run: ./gradlew :terpal-sql-native:mingwX64Test --stacktrace -PisCI -Pnosign
